NuvemaTown_MapScripts::
	.byte 0

NuvemaTown_WelcomeSign::
	msgbox NuvemaTown_Text_WelcomeSign, MSGBOX_SIGN
	end

NuvemaTown_Text_WelcomeSign::
	.string "Nuvema Town\n"
	.string "A town where various dots gather"

NuvemaTown_BiancaSign::
	msgbox NuvemaTown_Text_TownSign, MSGBOX_SIGN
	end
	
NuvemaTown_Text_BiancaSign::
	.string "Bianca's House"

NuvemaTown_CherenSign::
	msgbox NuvemaTown_Text_TownSign, MSGBOX_SIGN
	end
	
NuvemaTown_Text_CherenSign::
	.string "Cheren's House"

NuvemaTown_HilbertSign::
	msgbox NuvemaTown_Text_TownSign, MSGBOX_SIGN
	end
	
NuvemaTown_Text_HilbertSign::
	.string "Hilbert's House"

NuvemaTown_LabSign::
	msgbox NuvemaTown_Text_TownSign, MSGBOX_SIGN
	end
	
NuvemaTown_Text_LabSign::
	.string "Juniper Pokémon Lab"

NuvemaTown_PlayerSign::
	msgbox NuvemaTown_Text_TownSign, MSGBOX_SIGN
	end
	
NuvemaTown_Text_PlayerSign::
	.string "{PLAYER}'s House"
